behaviors:
    Hummingbird:
        trainer_type: ppo

        hyperparameters:
            batch_size: 2048
            buffer_size: 20480
            
            learning_rate: 3.0e-4
            learning_rate_schedule: linear
    
            beta: 5.0e-3
            epsilon: 0.19
            lambd: 0.92
            num_epoch: 3

        network_settings:
            vis_encode_type: simple
            normalize: false
            hidden_units: 128 # 256
            num_layers: 3
            memory:
                sequence_length: 64
                memory_size: 256


        max_steps: 5e6 # 5.0e5
        time_horizon: 128 # 64
        summary_freq: 10000
            
        reward_signals:
            extrinsic:
                strength: 1.0
                gamma: 0.99
